### ISSUE TITLE
Help - Mobile Synchronization talks about Calendar

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-contacts#102]
Cozy instance hosted on Cozy infrastructure (nicolas-6)
Data System: 2.0.3
Proxy: 2.0.0
Home: 2.0.2
Controller: 2.0.24
contacts -  1.1.4

Step to reproduce:
Open Contacts application
Clock on the Settings icon

What happens:
Settings are displayed, but the Mobile Synchronization talks about Calendar instead of Contacts (see screenshots below)
![capture du 2015-06-19 13-59-58](https://cloud.githubusercontent.com/assets/1799460/8253133/e86d4904-168c-11e5-93f2-0e21b3409073.png)

What sould happen:
Replace Calendar by Contacts.

I try to look within the code where that could be located. I though of `client/app/locales/` as it is localized, but I had no luck.
If you point out where this could be located, I'll be happy to propose a PR.

**Comment by poupotte** [comment]
This issue is deprecated with new version
