### ISSUE TITLE
Multiple records can be created when creating a new contact

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-contacts#107]
Steps to reproduce this bug :

- Create a new contact (+ button) and enter a name
- Enter a phone number and click outside of any entry field
- The new contact is created, but it stills active
- Enter another phone number, or populate any existing field
- Click outside any entry field
- A *second" contact has been created :-(
- Bottom line : Two contacts are now existing with the same name

**Comment by poupotte** [comment]
This issue is deprecated with the new version.
