### ISSUE TITLE
Cannot change the contact image anymore

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-contacts#124]
Hello there,

When I click on the contact picture to change it, the displayed modal is broken. When I click on it without the home top bar, it displays nothing.

What I recommend:

* fix the display bug
* have a traditional upload window as fallback when the modal is not available.

Frank

**Comment by clochix** [comment]
This issue is related to the new home modal: it seems this modal only works if the application is inside in an iframe inside Home ☹
Regarding the display bug, we should probably open another ticket in Home repository.

**Comment by frankrousseau** [comment]
No more relevant. I close this issue.
