### ISSUE TITLE
Base64-encoded picture in name fields

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-contacts#127]
![Uploading Screen Shot 2015-08-08 at 16.32.11.png…]()
Salut,

Ca fait un moment que je n'ai pas ouvert l'appli contact donc je ne sais pas a quelle version precise ca a beuger ni si s'en est une precise ou l'importation...

Actuellement je suis sous la versions 1.1.7

Tout mon probleme est dit dans la photos... J'ai l'impression que l'app veut passer la photo dans le nom... Peut etre un probleme de parsing?

cf -> [photo](http://picpaste.com/Screen_Shot_2015-08-08_at_16.32.11-80lGNgJZ.png)

**Comment by clochix** [comment]
Hello @Peltoche,
Il semble effectivement y avoir eu un problème d'import de test contacts. Est-ce que tu les synchronises avec une autre application ?
Lorsque tu affiches le détail d'un contact, est-ce que la version encodée de la photo apparait quelque part ?
Éventuellement, est-ce que tu pourrais exporter un de tes contacts et nous l'envoyer ?

Merci de ce rapport !

**Comment by Peltoche** [comment]
```
BEGIN:VCARD
VERSION:3.0
UID:59a05e92f605fc63e28f9cd91009f865
FN:Maxime Aubry Stiffler
N:Aubry Stiffler;Maxime;;;/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgY,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQ [...]
END:VCARD
```

**Comment by clochix** [comment]
Hello,

Le format du champs N dans le fichier me semble invalide, est-ce que tu sais comment tu as créé / importé ce contact ?

**Comment by Peltoche** [comment]
Hum... Je crois que a la base je l'ai importer d'une app sur telephone apres j'ai fais plusieur import/export avec contact. Sachant que la premiere fois tout allait bien la premiere fois (de souvenir) je pense que c'est votre module d'exportation qui n'est pas compatible avec celui d'imporation (c'est bete quand meme :smile: ) ou qu'il y ai un petit bug de parsing quelque part.

Bonne chance pour le retrouver! Je peux essayer de reproduire plus precisement le bug mais ca risque d'etre chaud pour trouver le pattern reproductible.

**Comment by Peltoche** [comment]
En fait j'ai save le fichier que j'ai importer : 
```
BEGIN:VCARD
VERSION:3.0
UID:874956d0e7320cf508e2ca50b300fa96
FN:Maxime Aubry Stiffler
N:Aubry Stiffler;Maxime;;;/9j/4AAQSkZJRgABAQAAAQABAAD/ [...]
```

Donc l'export cozy m'as donner cela. Je connais pas bien la syntaxe mais on dirait que le probleme vient de la, ce qui a fait planter l'import apres.

**Comment by Peltoche** [comment]
Le bug est assez simple en faite: le nom et le prenom sont bon dans le contact par contre la photo est passé dans le suffix. Sachant que le format de base dans le menu de gauche est Nom Prenom , Suffix on retrouve la photo dans le menu

**Comment by gregorylegarec** [comment]
Bonjour @Peltoche,

Je suis en train de regarder cette anomalie et j'ai besoin d'éclaircir un point : tu obtiens cette VCARD lors d'un export depuis Contacts ?
```
BEGIN:VCARD
VERSION:3.0
UID:874956d0e7320cf508e2ca50b300fa96
FN:Maxime Aubry Stiffler
N:Aubry Stiffler;Maxime;;;/9j/4AAQSkZJRgABAQAAAQABAAD/ [...]
```
Car de mon côté je n'obtiens pas du tout le même type d'export avec Contacts et je ne suis pas sûr de bien comprendre ta description vu que tu parles également d'application externe.

Merci de ta réponse !

**Comment by Peltoche** [comment]
Salut @gregorylegarec,

Mon probleme a ete probablement corriger depuis le temps, mais je n'ai pas retenter... Si je me souvient bien il y avait un probleme avec l'export de contacts sous format VCARD, quand j'exportais des contacts depuis Cozy et les reimportaient le contenue de la photo passait dans le titre, du coup j'avais un titre super long en hexa. Pour savoir si c'etait l'export ou l'import qui plantait j'avais essayer d'exporter depuis Cozy et importer dans Google ca plantait aussi. Par contre si j'exportait depuis Google et j'importais dans Cozy ca marchait, donc il semblait que l'export avait un probleme.

Mais vue la date tout ca est probablement resolue depuis un bon moment, sauf si tu as des nouveaux cas.

**Comment by gregorylegarec** [comment]
Merci @Peltoche pour ta réponse.

En effet le bug était encore sur notre liste d'attente et je n'avais pas fait attention à l'année, juste au mois. :)

Désolé de t'avoir dérangé et encore merci.

**Comment by gregorylegarec** [comment]
Issue fixed in current version.
