### ISSUE TITLE
Issue validation import

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-contacts#129]
Salut!

Je suis sous la version 1.1.7 et je bouton "Import" pour l'import des messages ne réagis pas.

**Comment by Peltoche** [comment]
Corrigé par clochix apparement.

Par contre il y a le bouton "Import" qui reste et si on clique dessus il semble relancer l'import mais a partir d'ou il est deja actuellement. J'ai spammé le bouton pour test est l'app a crasher -> desinstalle/reinstall et c'etait bon.

**Comment by Peltoche** [comment]
J'ai retesté sans spammer le bouton "Import", tout s'est bien passé mais apres rafraichissement l'app est crashé...

Ps: C'est peut etre lier au faite que j'ouvre la frame dans une nouvelle page pour contourner le probleme du message 1 du file car Clochix n'a pas encore pousser la correction.

**Comment by clochix** [comment]
Hello @Peltoche,
Il faudra retester une fois le ticket #126 résolu.
Tu dis que l'application est « crashée » après rafraichissement. Comment cela se manifeste-t-il ? Y a-t-ils des logs d'erreur sur le serveur ?

**Comment by poupotte** [comment]
Le ticket #126 est maintenant résolu. Du nouveau @Peltoche  ?

**Comment by Peltoche** [comment]
Il semblerait oui :). Je close le ticket du coup.
