### ISSUE TITLE
Error parsing Import

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-contacts#130]
Salut, 

Voici l'extrait de fichier a import qui a fait planter, ce fichier a ete generé par une app extern donc je sais meme pas si il est bien parser d'origine.
```
BEGIN:VCARD
VERSION:3.0
FN:Mathieu Morel\, /9j/4AAQSkZJRgABA 
[.... suite image ...] 
--

```

Apres l'import le contacte me donne pour titre: 
```
Mathieu Morel, /9j/4AAQSkZJRgABAQAAA [... suite code image ...]
```
Ca fait un gros titre...

**Comment by Peltoche** [comment]
Par contre c'est juste un cas unique, j'ai d'autres contactes qui on des sont paser pareil mais dont la photo a juste été ignoré: 

```
BEGIN:VCARD
VERSION:3.0
FN:Orlane Lebouteiller\, /9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQ [... suite image ...]
```
Dans ce cas la photo est juste ignoré... Une histoire de "magique number"??

**Comment by Peltoche** [comment]
J'ai testé avec une autre app, qui a un autre parsing:
```
BEGIN:VCARD
VERSION:2.1
N:Aubry Stiffler;Maxime;;;/9j/4AAQSkZJRgABAQAAAQABAAD/ [... suite image ...]
```
Donne dans le menu de gauche:
```
Aubry Stiffler Maxime ,/9j/4AAQSkZJRgABAQAAAQABAAD
```
Dans le contact le nom et prenom (Maxime/Aubry Stiffler) sont bien placer mais la photo passe dans le suffix.

**Comment by poupotte** [comment]
@Peltoche ce bug date d'avant la réécriture de l'application Contacts, est-ce que tu as encore le problème (si tu peux encore le reproduire) ?

**Comment by Peltoche** [comment]
Impossible de reproduire donc je pense que c'est ok.
