### ISSUE TITLE
Improve contacts sort

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-contacts#143]
I have a contact named 'paul' and an other contact named 'pauline'
In cozy-contacts : 'paul' is displayed after 'pauline'
If I synchronized my contacts in my phone : 'paul' is displayed before 'pauline'
Thus, in first time, I was thinking 'paul' wasn't synchronized with my phone

In my mind, phone sort is more logic than cozy-contacts sort.

**Comment by m4dz** [comment]
Agree, probably due to my temporary use oof localeCompare for sorting. I'll improve that quickly :smile:. Thanks !

**Comment by poupotte** [comment]
This issue is fexed.
