### ISSUE TITLE
Irrevelant search

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-contacts#170]
The search process is not very relevant. If I enter "paul", all contacts containing the letters p, a, u and l in their names (any order) are displayed ! Pretty useless.

I 'd rather like to see all contacts containing the *word* "paul" instead, in *any* field (ie not limited to name).

**Comment by clochix** [comment]
Thanks for your feedback @f6fvy.
I think @m4dz worked on it this week, so improvements are coming soon ☺

**Comment by m4dz** [comment]
Absolutely :smile:! I'm currently working on. If everything goes well, it'll be available for the next release :wink:.

**Comment by f6fvy** [comment]
Very good ! I'll wait patiently the next release. Thanks !

**Comment by f6fvy** [comment]
Several releases passed since Oct 30, and still no improvement on this matter. Just saying ;-)

**Comment by clochix** [comment]
Hi @f6fvy, sorry for not giving any news. Unfortunately, we had to update our priorities, and didn't find time yet to release the search improvements. But it's still on our roadmap and we hope to release it soon. Stay tuned ;-)

**Comment by poupotte** [comment]
Hi @f6fvy , in new Contacts version, there is a score for search. In other words, if you search 'paul', first results correspond to contacts called 'paul'. 
We want to add a limit of score to remove irrevelant results, see https://github.com/cozy/cozy-contacts/issues/222, what do you think about that ?

**Comment by f6fvy** [comment]
Hi @poupotte - Much better now indeed, and adding a minimum score is probably desirable. But, please consider also including other fields, like organization or notes, in the search process.

Use case : I entered a contact from a guy working at Tartempion Inc, but I can't remember his name and I need to call him...

**Comment by poupotte** [comment]
Hi @f6fvy , we published a new Contacts version (2.1.9). In this new version, we can search on other fields than name.

**Comment by f6fvy** [comment]
Hi @poupotte - Thanks !
