### ISSUE TITLE
Be more laxist when importing VCF file

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#171]
For now, we first check that file name ends with `.vcf` or `.vcard`, which is not really relevant, then check file content against a regular expression.
I think we should remove this tests and better handle exceptions when parsing the file, so the import won't fail if a contact is not well formated in the file (or if our library is unable to read it).

Also we should use better error messages.

**Comment by m4dz** [comment]
I agree, but errors should probably better be handled in the cozy-vcard parser (actually it's just a `console.error` call), so apps using the lib may catch errors and deal with them.

**Comment by m4dz** [comment]
No more tests on file ext are performed.

**Comment by clochix** [comment]
Thanks!
