### ISSUE TITLE
Slow merging

### ISSUE THREAD

**Issue by Gara64** [cozy/cozy-contacts#179]
After importation of a lot of contacts (~600), the merging is very slow for each duplicate, and tends to freeze the browser.
As I have dozens of duplicates, it's a bit difficult to manage :)

**Comment by doubleface** [comment]
Le problème est visible même pour 250 contact en ce qui me concerne. Suffisamment pour qu'on se demande si l'appli n'est pas plantée.

**Comment by clochix** [comment]
Thanks for reporting and confirming.
@m4dz would you maind having a look at this one ? Thanks !

**Comment by nicofrand** [comment]
See https://forum.cozy.io/t/contacts-sur-consommation-cpu-de-firefox/1567/4?u=nicofrand.
I provided a profile of the performances while merging 2 contacts from a list of 728 contacts.

**Comment by ArchangeGabriel** [comment]
I had to tell Firefox to continue executing the script three times for each merge. This is indeed very annoying. ;)

**Comment by jsilvestre** [comment]
This has been taken into account in #228, so we close here.
