### ISSUE TITLE
Cannot import a vcf file with \r\n lines terminator

### ISSUE THREAD

**Issue by alpha14** [cozy/cozy-contacts#180]
Error displayed : "The uploaded file isn't a valid VCF/VCard format."
Test file : https://gist.github.com/anonymous/de270cfeb839f1dcd452

**Comment by clochix** [comment]
Hi @alpha14,

I'm unable to reproduce this error with your test file.
We perform two tests before trying to import the file: https://github.com/cozy/cozy-contacts/blob/f761c53d71ea7ca929bf573e96a0b5a689b6491c/client/app/views/models/app.coffee#L105
 - check file extension;
 - check file content with a regexp.

Could you perform both tests on your test file. Also, could you check that the file you're trying to import doesn't contain any non ASCII character that the regexp may not like?

**Comment by alpha14** [comment]
Hello @clochix,

My bad, i didn't test with the uploaded file.
It's my contact app on android that actually produces a VCF file with \r\n for newlines.

**Comment by clochix** [comment]
@alpha14 do you mean it works if we use \n for newlines, but not with \r\n ?
A user reported once such a problem but we was never able to reproduce it, so I would be very interested if we could investigate this deeper.
Thanks for your help !

**Comment by alpha14** [comment]
@clochix: yes, I just tried with my contacts file stripped of '\r', works like a charm.

**Comment by frankrousseau** [comment]
Great, thank you both!

**Comment by aenario** [comment]
I think it's still actually a bug with vcard files containing "\r\n" instead of "\r", which could happen frequently on windows system. Supporting it is cheap, let's do it.

**Comment by dkm** [comment]
Same here. After changing line ending, vcf is imported as expected.

**Comment by clochix** [comment]
@m4dz did you remove the regular expression used to validate the VCF file, in the soon to be released next version?

**Comment by m4dz** [comment]
Not at this time and currently the release will probably be delayed later due to some remaining bugs… More coming soon :smile:.

**Comment by clochix** [comment]
Ccing @dkm who also reported this issue.
