### ISSUE TITLE
Adr datapoints value is String instead of Array

### ISSUE THREAD

**Issue by jacquarg** [cozy/cozy-contacts#182]
Previous version used Array to store Addresses. This one use String to store addresses, and cozy-mobile doesn't actually support it (hang on initialisation...). Cozy-vcard may have troubles too.

What is the way to write adress now ? Still Array or back to String ?

**Comment by clochix** [comment]
@m4dz could you have a look at this please, it's impacting users of the mobile app…

**Comment by m4dz** [comment]
@clochix yep, i'll do it quickly

**Comment by poupotte** [comment]
This issue is now fixed. Thanks @m4dz
