### ISSUE TITLE
Importing "large" vcf triggers "long runnning script" warning in firefox

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-contacts#192]
When importing a VCF with nearly 200 contacts, the process is rather slow, and after some time, firefox complains about the javascript executing for a long time (with the popup asking for "wait a bit more" or "stop script").

**Comment by clochix** [comment]
Thanks for reporting @dkm 
We are aware of performance issues when importing large VCF files, and @m4dz is working on it. A new version of the application should be available soon that we home will fix this.

**Comment by poupotte** [comment]
This issue should be fix on new version (2.1.6). @dkm : it's ok for you ?
