### ISSUE TITLE
Title of the page

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-contacts#204]
The title of the page is "cozy-contacts". This is due to cozy-scripts' HTMLWebpackPlugin configuration that should be fixed in https://github.com/CPatchane/create-cozy-app/pull/627.

This issue is just to check if updating cozy-scripts fixes the problem in cozy-contacts.

**Comment by y-lohse** [comment]
(The title is correct now, so I'm assuming it did fix the problem.)
