### ISSUE TITLE
Some fields are not displayed after contact creation

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#206]
Reported on [the forum](https://forum.cozy.io/t/app-contacts/1103/99):
Create a contact, fill some fields and add a tag, then save the contact, and edit it : only the firstname and the tag are displayed. (other fields have been saved, you can see them if you reload the page).
This seems to only happen when I add a tag.

Maybe related: when I create a new tag, it doesn't show up in the tag list, so I don't know if it has been added or if something failed. If this is unrelated to this issue, please open a new one.

**Comment by poupotte** [comment]
Fix on new version (2.1.6)
