### ISSUE TITLE
Avatar when contact name is long 

### ISSUE THREAD

**Issue by Crash--** [cozy/cozy-contacts#212]
A picture is better than words. 

![capture d ecran 2018-07-19 a 08 30 07](https://user-images.githubusercontent.com/1107936/42925587-f9749684-8b2e-11e8-92b4-7df150fbfc64.png)

**Comment by y-lohse** [comment]
Hi @Crash-- , thanks for the report! We've logged the issue on our internal bug tracker and will let you know here once it's fixed.

**Comment by JF-Cozy** [comment]
Fixed with https://github.com/cozy/cozy-ui/pull/1501
