### ISSUE TITLE
Truncate long email addresses

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#219]
Long emails addresses (such as github automate sender) broken rendered layout. We need to truncate them and find a way to view them full, copy, etc (tooltip, action button, whatever). ~~@kelukelu any thoughts about it?~~

Ok, so we just force wrapping in multiple lines :+1:

**Comment by poupotte** [comment]
I close this issue it's a duplicate of https://github.com/cozy/cozy-contacts/issues/158
