### ISSUE TITLE
Import data from Google and other providers (FB etc.)

### ISSUE THREAD

**Issue by mihneadb** [cozy/cozy-contacts#22]
I think it's worth reusing/looking at the code that does this for Firefox OS:
https://github.com/mozilla-b2g/gaia/blob/master/apps/communications/gmail/js/gmail_connector.js

There's a FB connector in there too.

**Comment by jsilvestre** [comment]
There is now a way to import contacts from Google and all through "import from google" and connectors, so I close this issue.
