### ISSUE TITLE
Tag doesn't pop in suggestion list at creation

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#220]
**Problem**

When creating a tag, it doesn't pop into the suggestion list if its already present in the DS

**Step to reproduce**

1. edit a contact
2. dropdown the tags list
3. create a tag that already exists in the DS but that isn't already linked to a contact (so _not_ visible in the drawer)
4. the contact is properly added to the contact, but doesn't pop into the list

**Solution**

The tag collection filter needs to be revamped to handle this use case

**Comment by poupotte** [comment]
This issue seems fixed now.
