### ISSUE TITLE
Limit search to a median result

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#222]
When doing a free-typed search, search results are sorted by a score, computed from the matching pattern. As long as you type, your search'll be more accurate, so first results tends to have a high score. To limit noise with end-list containing irrelevant search results, I suggest we limit the results to ½ of the higher score if this one is higher than 5.

**Example**

We make a search on the string `example`. If the first result have a score higher that `5` (say `30`), we cut the results list to items with a score <= `15`.

**Comment by poupotte** [comment]
Fix on new version (2.1.6). Thanks @m4dz !
