### ISSUE TITLE
web browser heavy load at import

### ISSUE THREAD

**Issue by dkm** [cozy/cozy-contacts#226]
when importing a VCF with ~100 entries, the browser begins to slow down really hard (it is not usable).
Memory usage grows as long as contacts are being imported.

When importing is finished, browser comes back to life.

Browser is iceweasel 44.0b6

**Comment by clochix** [comment]
Hi @dkm,
Thanks for reporting. We are currently working hard to improve performances of the application, we hope to publish a new, more reactive version, very soon.
Stay tuned ;-)

**Comment by poupotte** [comment]
This issue should be fixed on new version (2.1.6). @dkm, is it ok for you ?
