### ISSUE TITLE
When user hasn't contacts in his cozy, we shouldn't display letters.

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-contacts#227]
![screenshot from 2016-01-19 15 36 32](https://cloud.githubusercontent.com/assets/2659119/12515412/9446994c-c128-11e5-9609-8c8dc6f3ac7d.png)

**Comment by frankrousseau** [comment]
I can't reproduce the issue. Do you have any idea of how I could reproduce it?

**Comment by clochix** [comment]
Unable to reproduce, when I have no contact, the indexes are hidden.

**Comment by poupotte** [comment]
Same here, I don't arrive to reproduce. I propose to close this issue, if someone has this issue, don't hesistate to reopen it !
