### ISSUE TITLE
Changing once a contact trigger two `change`events

### ISSUE THREAD

**Issue by misstick** [cozy/cozy-contacts#235]
1. I click on 1 contact,
2. I click on a tag,
3. the tag is added in the card,
4. `updateTags` is called once,
5. model ‘contact’ is changed once,
6. `contact.change`event is recieved twice.

I seems to come from this :
`@listenToOnce @, 'sync', -> @contactListener.watch @`
client/app/collections/contacts.coffee l51

**Comment by m4dz** [comment]
The recent refactor of [models events lifecycles](https://github.com/cozy/cozy-contacts/commit/3f32a3d4a98a1f2b94a825a3589a1c6dbd00d490) should have fixed this one.
