### ISSUE TITLE
Incremental building is 5/6sec

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-contacts#246]
I used `yarn watch --hot` to work on contacts.

When I change something small like a text in a JSX node, I had lengthy incremental build times.

```
Hash: b38d9f2b222f342c7aa6
Version: webpack 3.12.0
Child
    Hash: b38d9f2b222f342c7aa6
    Time: 4947ms
```

I think it can be made much smaller, something must be wrong.

**Comment by enguerran** [comment]
The build (build or watch) uses [cpatchane/create-cozy-app](https://github.com/cpatchane/create-cozy-app) ([build](https://github.com/CPatchane/create-cozy-app/tree/master/packages/cozy-scripts#--cozy-scripts-build) or [watch](https://github.com/CPatchane/create-cozy-app/tree/master/packages/cozy-scripts#--cozy-scripts-watch)).

cf. https://github.com/cozy/cozy-contacts/blob/master/package.json#L14

There is no configuration on the project. So to enhance thoses processes, two solutions are possible:

1. take back the bundle building responsibility ;
1. open (and wait for a fix) an issue on  [cpatchane/create-cozy-app](https://github.com/cpatchane/create-cozy-app).

**Comment by Crash--** [comment]
I close this issue since now the incremental build is around ~1200/1500 ms. I think we can improve this time again, but not in a near future ;) 

```
App successfully updated!

  Dev assets:        http://localhost:8888
⚠ ｢wdm｣: Hash: 5180c3a5b789ae2f13a4
Version: webpack 4.25.1
Time: 1400ms
Built at: 2018-11-12 14:56:16
```
