### ISSUE TITLE
Bulk action delete fails if called on a single contact

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#246]
If the user selects only one contact, then the *delete* action (which called the bulk delete) failed.

**Comment by frankrousseau** [comment]
I think it's related to a wrong build. In development everything works fine.

**Comment by m4dz** [comment]
@frankrousseau good news! To test with the next build so.

**Comment by aenario** [comment]
@m4dz : I dont understand, does the fix from this morning fix it for you ? If could you please close this issue :heart:  ?

**Comment by m4dz** [comment]
With all my :heart:, sweeties :smile:!
