### ISSUE TITLE
Clicking a contact doesn't open it (Android / Firefox)

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-contacts#26]
Confirmed on Android 4.3 and 4.4

**Comment by frankrousseau** [comment]
Yes it's still not working.

**Comment by frankrousseau** [comment]
Maybe @jacquarg could work on it?

**Comment by jacquarg** [comment]
Yes !
With Joseph's advices, and luck I think I fixed it with a simple update of nicescroll plugin. I PR as soon as the big PR#59  is merged.

**Comment by frankrousseau** [comment]
Ok. Thank you for the update.
