### ISSUE TITLE
Bad contact title

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-contacts#35]
When I import some card, titles are KO.

Some times only a ",".

Or "Centre equestre Chateaubourg,  " and if I try to fix card to "Centre equestre Chateaubourg" all title disappear.

Can I force the title?

Examples are here:
https://nicolasledez.cozycloud.cc/public/files/files/e64954041db6688556e0621324283e6a/attach/ContactNoSummary.vcf

**Comment by frankrousseau** [comment]
Could you test again with recent changes?

**Comment by clochix** [comment]
Dear @jsilvestre, dear @nledez, I would really appreciate if you could give import another try and tell us if you still encounter this behavior. Thanks !

**Comment by frankrousseau** [comment]
We have no news from both of them, let's consider the issue closed.
