### ISSUE TITLE
Note field doesn't save properly

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-contacts#39]
There is a case where the note field is not properly saved:

1. Click on a contact that has no notes already set.
2. Type a note on it
3. Focus out of the field

The result is that the note field is automatically cleared and your note data are lost.

**Comment by clochix** [comment]
@frankrousseau do you still experiment this bug or can we consider it has been fixed ?

**Comment by frankrousseau** [comment]
No, thank you!
