### ISSUE TITLE
Exporting contacts by tag

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-contacts#42]

**Comment by Beast141** [comment]
You know this would be very useful if the 'Group' the contacts are listed under in android are then imported in Cozy in tags. so Group = Tags, would be really amazing enhancement.
Dont you think?

**Comment by hansbkk** [comment]
Sounds great. IMO should support (in both directions, export and import/sync)  both Google and iCloud style group specs, lots of tools use the "category" field to emulate tags/groups with vCard 3.0, but in the future native v4.0 Groups support will be needed.

**Comment by poupotte** [comment]
It's now possible with new version :)
