### ISSUE TITLE
Impossible (?) to remove all contacts at once

### ISSUE THREAD

**Issue by bagage** [cozy/cozy-contacts#43]
I imported my contacts from a `vcf`and now I would like to remove them all (because some are missing and I don't want to mess with duplicates etc.). I could not find an option via the webapp to delete them all?

**Comment by nicofrand** [comment]
It is a duplicate : https://github.com/cozy/cozy-contacts/issues/111 (for the mass delete part)

**Comment by poupotte** [comment]
We can now delete all contacts with new version.
