### ISSUE TITLE
Contact import do not support char encoding field

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-contacts#44]
l s'agit d'un format de vcf de ThunderSync de TB qui exporte en version 2.1 et on y remarque la mention ;CHARSET=UTF-8 qui fait buger l'import du nom un coup de sed dans le fichier et hop c'est repartie.

BEGIN:VCARD
VERSION:2.1
REV:2014-12-19T12:40:45Z
N;CHARSET=UTF-8:NOM

**Comment by jsilvestre** [comment]
Is it still bugging?

**Comment by clochix** [comment]
@frankrousseau do you still experiment this bug or can we consider it has been fixed ?

**Comment by frankrousseau** [comment]
Don't know I reported it from a user email.

**Comment by aenario** [comment]
CHARSET=UTF8 should have been fixed by : https://github.com/cozy/cozy-vcard/commit/9e243bc1783b90ee6014053d785dc79625892419

I suggest we close this issue in favor of #45 where we have a participating user.

**Comment by frankrousseau** [comment]
Ok thank you @aenario for the info.
