### ISSUE TITLE
When importing - the labels 'Home' turns into 'Voice'

### ISSUE THREAD

**Issue by Beast141** [cozy/cozy-contacts#57]
When importing all contacts at once or even one at a time - if the contact was saved with a Home number in android with the 'Home' label. on cozy it shows 'Voice' and then once i go add an additional number on that specific contact on cozy - after changes have been saved it automatically duplicates the name of the contact. Very weird.. perhaps a bug?

**Comment by Beast141** [comment]
I have come across an additional bug - once i change the cell phone number on cozy - it automatically duplicates the name again. i see it has duplicated the firstname into family name. Since there was no family name.  Why does it do this?

**Comment by jsilvestre** [comment]
Hi @Beast141 and thank you for the report. We are currently in the process to clean up name management, that should fix your name bug. About the label change, we'll have a look at it (ping @jacquarg).

**Comment by jacquarg** [comment]
Hi. I made a fix about the labels this morning. I hope that the next update will fix the two bug you have found.

**Comment by clochix** [comment]
@jsilvestre, @jacquarg any news on this ?

**Comment by jacquarg** [comment]
I put a fix with PR #59 . But it's a quick (and dirty ?) fix : types home, work, and cell have priority, others are hidden.  
A new issue (#6) in cozy-vcard asks to get further on this subject: handle multi-types.

**Comment by clochix** [comment]
Hi @Beast141, could you please update Contact and test if the latest version fix this issue ? Thanks ☺

**Comment by Beast141** [comment]
Hi there - sorry for the delay, it seems as though after the update it didnt change/correct my current contact list.  I am looking for a way to mass delete all contacts and re import them but i cannot do that to test. i can however test one contact and i will give feedback shortly.

**Comment by Beast141** [comment]
Okay - i managed to delete all contacts with the data browser and re-imported them all. It now works. Thank you so much Cozy team for making Cozy better everyday!!

**Comment by frankrousseau** [comment]
Great, thank you for the bug report!
