### ISSUE TITLE
Improve card deletion

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#66]
Deleting cards is not truly intuitive: we must go to "more infos" section to get access to the delete button, which isn't totally relevant. Plus, have a way to bulk delete files could be a good and faster way to quickly edit the list.

**Comment by frankrousseau** [comment]
+1

**Comment by Beast141** [comment]
i bump this enhancement as soon as possible! Having a mass deletion would be extremely useful. As well as an easy deletion button.

**Comment by Peltoche** [comment]
Hi! 
I want delete all my 399 cards, you can imagine that will be very long if i delete them one by one... That should be great than we can select list and after do an action. An one button to erase all.
Thks for the work!

**Comment by brouberol** [comment]
Let me wholeheartedly +1 this.

**Comment by poupotte** [comment]
This issue is deprecated with new version.
