### ISSUE TITLE
Keyboard navigation in form

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-contacts#68]
Using Firefox, its not convenient to navigate using tab in contact edition form. (stuck in name field, stuck in tags field)

While we are at it, we might want to implement keyboard navigation in contacts list.

**Comment by Bobbylamouche** [comment]
I agree with this one. The user should be able to tab from one field to the other, especially on the same line. For example: when I enter a new phone number, I have to fill the type of phone (main) then the number itself. A Tab should take me to the first field to the second.

**Comment by poupotte** [comment]
This issue is fixed with new version :)
