### ISSUE TITLE
iOS custom fields cannot be saved 

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#74]
iOS uses vcard fields to store additional informations such as custom ring per contacts. If you try to set it to a contact synchonized with your cozy, the field isn't saved, and the contact fall back to its previous version, meaning you lack your custom setting.

**Comment by hansbkk** [comment]
Related to the general idea of "don't lose user data", if not preserving full vCard data intact (apparently not possible due to architectural choices) then working toward supporting at least the full set of fields used by Google Contacts and iCloud.

some others clustered here:
https://github.com/cozy/cozy-sync/issues/26#issuecomment-73535007

**Comment by frankrousseau** [comment]
@m4dz Could you provide an example of failing iOS vCard

**Comment by m4dz** [comment]
I will use wireshark to capture network stream from my iOS device to provide a guilty vCard to you ;)

**Comment by m4dz** [comment]
Ok, nevermind, I previously speak about [Charles](http://www.charlesproxy.com/documentation/faqs/using-charles-from-an-iphone/). I'll do it tonight of tomorrow morning :)

**Comment by frankrousseau** [comment]
I think there is a way to export your data directly to vCard format.

**Comment by m4dz** [comment]
Unfortunately, from iOS, I'm not sure the OS allow that. I can export a vCard from the contacts.app on OS X but there's a risk that the datas aren't truly identical.

**Comment by hansbkk** [comment]
the iCloud contacts interface should have an "export to vCard"

also many CardDAV clients will sync with the pretty-standard iClound interface at https://contacts.icloud.com - vdirsyncer will create a standard vCard collection against this, or act as an intermediary to sync against Radicale or SabreDAV for example.

**Comment by frankrousseau** [comment]
I don't have Apple hardwares of my own, so my iCloud account has close to no apps. I will deal with exports directly from an iPad I borrowed.

**Comment by hansbkk** [comment]
Then you should be able to use the sample "complete" Google vCard I created, import that into iCloud and have a look to see if Apple supports some additional fields.

I believe their structuring of the Groups feature is special to Apple's contacts, but many CardDAV clients support it, as well as the more usual use of Categories as groups.

**Comment by m4dz** [comment]
So (sorry for the delay) iCloud doesn't offer a mechanism to export a vCard. I used Charles as I mentioned above to spy exchanges between my iOS device and iCloud servers. The session is [attached to this post](http://cl.ly/1G3O382Z3s22/download/icloud_carddav.chls).

During this test, I tried to update settings related to the notifications sounds and vibrates. The vCard format posted in the `PUT` request is:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 8.1.3//EN
N:;M4D'z;;;
FN:M4D'z
PHOTO;X-ABCROP-RECTANGLE=ABClipRect_1&0&0&512&512&on/5YPQ6a2aqxD9H3Hg3OQ==;VALUE=uri:https://p02-contacts.icloud.com:443/294944289/wbs/01c11c4b48adb94d3577eb7c5b8aafa5c0b012fef5
REV:2015-03-04T13:01:17Z
UID:f5878541-e283-4299-90bf-851dcb484527
X-ACTIVITY-ALERT:type=call\,snd=system:Bulletin\,vib=Alert
X-ACTIVITY-ALERT:type=text\,snd=<none>
END:VCARD
```

So Apple uses the `X-ACTIVITY-ALERT` to save this kind of settings (`<none>`  here refers to `silent` sound notification for SMS).

**Comment by frankrousseau** [comment]
And they use URIs as picture.

**Comment by m4dz** [comment]
> And they use URIs as picture.

Indeed :smile:

**Comment by frankrousseau** [comment]
I close this @m4dz. Let me know, if you meet another problems

**Comment by m4dz** [comment]
Thanks a lot @frankrousseau! Everything seems all right now :smile:.
