### ISSUE TITLE
Bulk import failed on large amount of data

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-contacts#76]
Some users have encoutered silent import failures when trying to import bulk VCF files exported from Apple Contacts.app (see [Import contacts depuis Mac OS 10](https://forum.cozy.io/t/import-contacts-depuis-mac-os-10/376) [fr]). Import failed when there is many contacts (approx 200) in a single file. Small files (~70 contacts per each one) works-well. The limit isn't very clear (I have successfully imported a single 280 contacts file when others failed to import a 200 contacts files) and seems to be related to the amount of data instead of the number of contacts.

_Note_: I'll provide a fake VCF files for test.

**Comment by hansbkk** [comment]
Note many apps/platforms will only accept one-at-a-time VCF-per-contact, and a "standard" plaintext data store is "folder full of VCFs".

So there are plenty of tools that will split out from that to a single-file collection, or merge back.

Some like Markus Unterwaditzer's vdirsyncer 
	https://vdirsyncer.readthedocs.org/en/stable/vdir.html
and Annemarie Böhmer's ContactSync 	https://play.google.com/store/apps/details?id=com.vcard.android

actually let you sync between the two types of data store.


Just pointing this out to help you think outside the box in coming up with solutions.

**Comment by frankrousseau** [comment]
In fact the problem was solved yesterday night. I imported 500 contacts with 40 fields each. It's slow but it works.
