### ISSUE TITLE
Importing vCard with Google Chrome

### ISSUE THREAD

**Issue by AntoineCa** [cozy/cozy-contacts#79]
Importing vCard within contatcs works perfectly with Firefox but not with Chrome.
When selecting a .vcf, the import window displays "*xxx.vcf is not a vCard*".

**Comment by frankrousseau** [comment]
Ok.Thank you for reporting. We'll have a look a it soon.

**Comment by aenario** [comment]
Bonjour @AntoineCa, cela peut aussi être lié à l'OS. Lequel utilises-tu ?

**Comment by AntoineCa** [comment]
Windows 8.1 !

**Comment by frankrousseau** [comment]
We found the origin of the bug. It's because the mime type declared by Windows 8 for .vcf file doesn't match the one we set in the application.

**Comment by frankrousseau** [comment]
@AntoineCa It looks fixed, could you try again?

**Comment by AntoineCa** [comment]
It works perfectly :)
