### ISSUE TITLE
Bad URL for cozy-contacts homepage

### ISSUE THREAD

**Issue by nono** [cozy/cozy-contacts#86]
Hi,

nothing very important, but it can be nice to fix the homepage URL of [cozy-contacts](https://github.com/cozy/cozy-contacts) (at the top). It should be http://cozy.github.io/cozy-contacts/ instead of http://mycozycloud.github.io/cozy-contacts/.

**Comment by frankrousseau** [comment]
Thank you for reporting. I think this website is no more relevant. So I changed it to the main website.
