### ISSUE TITLE
Provide a tool that detects and merges duplicate contacts

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-contacts#88]
So Google added this in their "contacts preview" app, and it works pretty nicely. After some trials of their tool, I think their algorithm just checks whether full names of any pairs of two contacts are equal (first name + space + last name) and suggests to merge them afterwards (this can be done in O(n log n) time where n is the number of contacts).

**Comment by poupotte** [comment]
This feature was added in new version.
