### ISSUE TITLE
Import large vcf file renders browser unusable 

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-contacts#89]
Trying out cozy and importing a large vcard file (2600 contacts) renders my browser unusable on other tabs. The CPU could be a bottleneck as it is showing 100% on firefox in htop.

**Comment by arthurlutz** [comment]
Sorry a bit more information about my browser : Firefox 37.0.2+build1-0ubuntu with a bunch of extensions. I can provide extra information if needed.

**Comment by clochix** [comment]
We parse the VCard file in the browser before importing it on the server, so importing a large file may give some work to the browser.
If you let the browser work, does it perform the import after some time ?

@jsilvestre, do you think we could add a wait screen with a progress bar ?

**Comment by arthurlutz** [comment]
@clochix  the import takes a bit of time (that's ok) and works in the end, it just prevents the user from using his browser for other activities (I ended up firing up another browser for doing something else).

**Comment by clochix** [comment]
Thanks, so let's say this is an enhancement request ;-) We could try to use Web Workers to perform the import. Or wait for Electrolysis to land in Firefox stable (one thread by tab, currently available in Firefox Nightly)

**Comment by frankrousseau** [comment]
@arthurlutz Are you sure you have the latest version of Cozy Contacts? That problem was fixed one month ago. I tried with 3000 contacts, it was slow but the browser was useable. Maybe something broke...

**Comment by arthurlutz** [comment]
using Contacts -  1.1.4

**Comment by poupotte** [comment]
This issue should be fixed with new version.
