### ISSUE TITLE
Small update to do in github and French translation

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-contacts#91]
Hello,

In the Github page, the link to the solution to CardDav is still "Cozy Webdav" instead of "Cozy Sync" : CardDAV sync (it requires Cozy Webdav) . It's just before "Install".

Otherwise, in the french translation, when you use Contact, inside the Help Panel, when you explain how works the "Synchronisation mobile (CardDav)", you write "Pour synchroniser votre agenda, utilisez les identifiants suivant :" . You should replace "votre agenda" by "vos contacts".

Regards,
Thatoo

**Comment by frankrousseau** [comment]
Than you for reporting. Thatoo. The configuration screen requires some improvements.

**Comment by clochix** [comment]
@Thatoo thank you for reporting, I think everything has been fixed.
