### ISSUE TITLE
Phone icon's action is not working in Firefox OS

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-contacts#92]
Hello,

I don't know if the problem is from cozy or from FFOS, but when I click on the phone icon on the right side of a phone number of my contacts, in cozy-contacts, it open the FFOS phone app (that's great, I was really impressed) but it dial only "+", no number, just the +, not even +33, just +... (that's what we call an "ascenseur émotionnel", lol).

A bon entendeur,

Thatoo

**Comment by frankrousseau** [comment]
Don't know either, but that's something we should optimise. Thank you for reporting.

**Comment by nicodel** [comment]
Hi,
This is more not linked to FFOS.

An additionnal "+" is added before the number registered in the contact details. Consequences for FFOS:
* When a  number is registred as : 01 45 xx xx xx a "+" is added in front, the number displayed in the Phone application is "+01 45 xx xx xx".
* When a number is registered as : +33 1 45 xx xx xx the same "+" is added, and only "+" is displayed in the Call application.

I'll look in the code where it could be located to propose a fix.

**Comment by nicodel** [comment]
PR #116

**Comment by Thatoo** [comment]
Thank you!
I'll try as soon as an update of contacts come.

**Comment by nicodel** [comment]
Hi,

I updated Contacts to 1.1.6 and it is fixed. For both phone number format.

@Thatoo I let you test and close this bug if it works for you too.

**Comment by Thatoo** [comment]
It works!
Happy.
