### ISSUE TITLE
Suffix should be displayed in the contact list

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-contacts#96]
Contact suffix (Jr., Sr. or whatever) - if any - should be displayed in the contact list (left column) :

"John Doe, Jr". instead of "John Doe"

to help selecting the appropriate contact from the list.

**Comment by frankrousseau** [comment]
Thank you @f6fvy for the report.

**Comment by clochix** [comment]
Yeepee, it works, what a nice job, @poupotte ☺
@f6fvy can you confirm it now works as you expected ?
Thanks to both of you.

**Comment by f6fvy** [comment]
Much better ! Thanks.

Actually, there is a very minor glitch when there is only a first name and no family name, with a trailing space before the comma.

Ex : "John , Sr" instead of "John, Sr"

but I can live with it ;-)

Thanks again !
