### ISSUE TITLE
Contacts list mis-ordered when first name is empty

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-contacts#99]
When using the "First Name - Last Name" order, all contacts with empty First Names (companies etc.) are always displayed first, contrary to the Android order with the same settings.

For example:

Android order :

AUCHAN
Alain BABA
CASTO
John DOE

and CC order :

AUCHAN
CASTO
Alain BABA
John DOE

I guess the same glitch applies when using the Last Name - First Name order with contacts with empty Last Names (relatives, etc.).

(From https://forum.cozy.io/t/contacts-ordre-daffichage-de-la-liste/658/1)

**Comment by frankrousseau** [comment]
Ok thank your for the detailed bug report @f6fvy.

**Comment by clochix** [comment]
Thanks @poupotte, you fixed the sort ☺
@f6fvy can you install the latest version of Contact and confirm it works as expected ?

**Comment by f6fvy** [comment]
Very good now. Thanks !
